### ISSUE TITLE
systemctl issue

### ISSUE THREAD

**Issue by looffee** [archimg/archlinux#16]
When i'm run command like `systemctl start httpd.service` in container shell, i get error message `Failed to connect to bus: No such file or directory`. It's possible to solve this or its docker image limitation?

**Comment by bebehei** [comment]
Well, the image neither starts dbus nor systemctl. This is a docker-specific problem, what is unsolvable here.

**Comment by bebehei** [comment]
I can't tell you, what the exact problem is (i'll go to sleep now). But my main goal is to create a good archlinux docker image. I'm not sure why dbus does not work but I also never expected it to work.

Use something like supervisord to run miltuple services in one image. - For myself, on debian based images, this always worked perfectly for me.

**Comment by looffee** [comment]
ok, supervisord is good solution, thanks
