### ISSUE TITLE
Avoid "Read-only file system" error

### ISSUE THREAD

**Issue by dima74** [archimg/archlinux#22]
I want to change [TTL](https://en.wikipedia.org/wiki/Time_to_live#IP_packets) of archlinux docker container. But when I run command:

    echo 65 >/proc/sys/net/ipv4/ip_default_ttl

I got error:

> bash: /proc/sys/net/ipv4/ip_default_ttl: Read-only file system

Could you say, please, what should I do to avoid this error? Thanks a lot.

**Comment by bebehei** [comment]
Hey @dima74,

Docker containers are not allowed to change their network settings from inside. That would violate the requirement, to fully control the container from the host.

I'm not sure, what the correct option is, but one of them should work:
- Docker container invocation with `--sysctl` parameter: `docker run --sysctl net.ipv4.ip_default_ttl=65`
- You may have to add some network options to your docker network.
- You may want to give the container some capabilites to modify the network itself. [If I guess right, you may want to go for the `SYS_ADMIN` caps](https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities)
