### ISSUE TITLE
how to make docker image `archimg/base` work with nvidia-docker ?

### ISSUE THREAD

**Issue by homerhsing** [archimg/archlinux#25]
Hey ArchImg team,  somehow the docker image `archimg/base` does not work with nvidia-docker.

Run following command: 
`docker run --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=all -ti --rm archimg/base:latest nvidia-smi`
Get error:
`NVIDIA-SMI couldn't find libnvidia-ml.so library in your system. Please make sure that the NVIDIA Display Driver is properly installed and present in your system.
Please also try adding directory that contains libnvidia-ml.so to your system PATH.`

However `ubuntu:latest` docker image work with `nvidia-docker`
`docker run --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=all -ti --rm ubuntu:latest nvidia-smi` 
works.

Do you think there's some problem in the `archimg/base` image, or am I doing something wrong ? :slightly_smiling_face:

**Comment by hugendudel** [comment]
Hi @homerhsing ,

not sure what you expect.

I installed nvidia, you're missing the libraries
```
FROM archimg/base:latest
RUN pacman --noconfirm -Sy nvidia
```

build
```
docker build -t arch-nvidia:latest .
```
run
```
docker run --runtime=nvidia -e NVIDIA_VISIBLE_DEVICES=all -ti --rm arch-nvidia:latest nvidia-smi
Tue Aug 14 11:36:35 2018       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 396.51                 Driver Version: 396.51                    |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 107...  Off  | 00000000:01:00.0  On |                  N/A |
|  0%   47C    P8    10W / 180W |    784MiB /  8116MiB |      8%      Default |
+-------------------------------+----------------------+----------------------+
                                                                               
+-----------------------------------------------------------------------------+
| Processes:                                                       GPU Memory |
|  GPU       PID   Type   Process name                             Usage      |
|=============================================================================|
+-----------------------------------------------------------------------------+
```

regards,
Harm

edit:

Ahh sorry, you're missing the Nvidia driver.

**Comment by bebehei** [comment]
Sorry, I'm not running the nvidia-docker daemon, but I previously heard about it.

And if I get it right, all you have to do is simply installing the nvidia related packages, like @hugendubel did, right?!

If so, I don't see any motivation to provide an extra image. If there are still some other changes necessary, please let me know.

**Comment by homerhsing** [comment]
I see, thanks for the answers, @hugendudel :slightly_smiling_face:
