### ISSUE TITLE
Misleading tag names

### ISSUE THREAD

**Issue by CyberShadow** [archimg/archlinux#28]
It looks like a tag named YYYY.MM.01 will actually contain an image built towards the end of the YYYY.MM month. E.g. the tag 2018.12.01 was apparently last updated "3 hours ago".

Getting the date in the tag name to match the image content would be nice to minimize the overhead of updating to a point-in-time snapshot of the distribution using the Arch Linux Archive.

**Comment by bebehei** [comment]
Obviously this is a mistake of mine. I should have named them `2018-12` instead of `2018.12.01`.

There are actually two important layers: the daily one and the base one. The base layer contains the official tar image and also a full update when it's created. The daily layer is built on top of the base layer and is created daily. So when you do a `docker pull archimg/base`, you only have to download the daily layer.

So it's actually minified.

---

But anyways, have you evaluated [archlinux/archlinux-docker](https://github.com/archlinux/archlinux-docker)? I might even deprecate this repository.

**Comment by CyberShadow** [comment]
> There are actually two important layers: the daily one and the base one.

Ah, I missed those, as I was looking at https://hub.docker.com/r/base/archlinux/ . (Looking closer, that seems to link to this GitHub repo, but not the other way around - I'm guessing that's not your account?)

> But anyways, have you evaluated [archlinux/archlinux-docker](https://github.com/archlinux/archlinux-docker)?

Yes, that one doesn't seem to have tags at all. I filed an issue:
https://github.com/archlinux/archlinux-docker/issues/11

**Comment by bebehei** [comment]
Well, you're using archlinux. Having tags is actually a bad antipattern. But there wouldn't be another solution while requiring it to be built on publicly available infrastructure.

On Arch there is no point in having tags.

And also while reading your comment on the other issue. IMO it's not possible to combine docker and Arch in a reproducible Dockerfile. You should build the image, conserve it and upload it to dockerhub.

**Comment by CyberShadow** [comment]
> Well, you're using archlinux. Having tags is actually a bad antipattern.

For normal use, maybe.

For CI and reproducible processes, it is a hard requirement.

It would also be pretty useful for bisecting regressions.

> IMO it's not possible to combine docker and Arch in a reproducible Dockerfile.

It looks like it's possible to get there with some degree of success with the help of the Arch Linux Archive, which provides snapshots of the package repos with a day-by-day granularity; however, as the span of time for the up/downgrade increases, the chances of a successful non-interactive up/downgrade seemingly decreases.

I think starting with a specific tarball is on the right track; then, changing the pacman mirrorlist to point to the ALA would be the next step.

**Comment by bebehei** [comment]
Ok, this isn't this repository's business.
